### PR TITLE
updated 5 year ACS data for 2013-17

### PR DESCRIPTION
**Pull request by ocarena**
@ptatian I got this far on the 5 year ACS 2013_17 update but I had a question on part 6aii of the instructions (https://urbanorg.app.box.com/notes/51315236817?s=qejvsul03ecv4u8xny3xftjtdot0xeo3). I started with the DC log and realized there were several variables with 0 nonmissing observations. I wanted to make sure I wanted to clarify that make sure I kept/dropped the right variables and was sure of the procedure with DC before moving to the other states.

### CODE REVIEW

**Comment by ptatian** [comment]
Thanks, @ocarena. Can you list a few examples of vars with 0 nonmissing?

**Comment by ocarena** [comment]
@ptatian I may be misinterpreting the proc means statement, but I think several examples include: 
B05006e1, B14001e1, B27001e1. Let me know if I'm reading this wrong

**Comment by ptatian** [comment]
@ocarena These are probably tabulations without block group data. Census doesn't document that very well, but some tables only have data for tracts or larger units. We've been moving away from using the block group data, so it's less critical than it used to be. Can you check the Proc Means output for the data sets created from the tract data (i.e., the data sets with _TR_ in their names) to see if they have 0 nonmissing? If the tract data looks good, I would say we don't need to worry about this. cc: @rpitingolo

**Comment by ptatian** [comment]
Thanks, @ocarena  It sounds like we can just proceed without doing anything further on that. Given that, are you ready for someone to review the programs? Cc: @rpitingolo

**Comment by ocarena** [comment]
@ptatian @rpitingolo Yes! These programs are ready to be reviewed.

**Comment by rpitingolo** [comment]
@ptatian @ocarena I can review.

**Comment by rpitingolo** [comment]
@ocarena it looks like Acs_sf_2013_17_ss.sas is a template that is not used, so please delete it and then commit. After that this looks good so please go ahead and merge the branch, run sync.bat on L and the batch submit. 

After that you can move on to the next issue. Thanks!

**Pull request merged**
