### PR TITLE
Enhancement #88

### PR DESCRIPTION
**Pull request by lhendey**
@rpitingolo - can you take a look at this? I am getting errors when the program hits the %transform geo macro - but I'm not sure why. (I don't think i changed any parameters going into it).  i did move some vars from the geo_source_bg to geo_source tract but I edited the summary_geo program to deal with those.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@lhendey OK. Should I test using ACS_2012_16_dc_sum_all.sas ?

**Comment by lhendey** [comment]
@rpitingolo yep

**Comment by rpitingolo** [comment]
@lhendey OK. I'll look now.

**Comment by rpitingolo** [comment]
@lhendey there was a missing semicolon in ACS_summary_geo_source_tr_vars.sas. I added it and pushed the committ. It runs through for me now. Can you take a look to see if this solves your issue?

**Comment by lhendey** [comment]
@rpitingolo - yes errors resolved, thanks. I'm getting a few uninitialized vars so I'll check those out.

**Comment by rpitingolo** [comment]
@lhendey I saw the uninitialized vars but wasn't sure if you already knew about them / had a plan to resolve so I didn't touch them.

**Comment by lhendey** [comment]
@ptatian -  tried to adjust [acs summary geo](https://github.com/NeighborhoodInfoDC/ACS/pull/102/commits/20d0d756ec9f6b892b899dddaef18376d8ef071d)
 to subset weight file - issue is on council district file. no errors in log and looks like base and comparison files have the same N but - data is not adding up.  thoughts? using 
D:\DCDATA\Libraries\ACS\Prog\SF_2012_16\ACS_2012_16_md_sum_all.sas to test on enhancement-#88

**Pull request merged**
