### PR TITLE
ACS geo summary file update 2015-19 5 year estimates

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo ready for your review!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 great! Will review now.

**Comment by rpitingolo** [comment]
@ahariharan7 Can you please make sure all the programs have the updated \\sas1\dcdata header?

I need to check the macros because I am seeing an uninitialized variable warning for the 2 variables that ACS doesn't include anymore.

**Comment by rpitingolo** [comment]
@ptatian can you please help weigh in on a ACS data change? Census discontinued B00001 and B0002 (unweighted pop and housing unit counts) and replaced them with B98001-B98003 but only for Nation, State, County, and Place. https://www.census.gov/programs-surveys/acs/technical-documentation/user-notes/2020-05.html

Would you vote to update the macro so that starting with 2015-19 it includes unweighted counts on the county summary files (but not the others) or omit it from all the geographies for consistency? 

@lhendey @ahariharan7

**Comment by ptatian** [comment]
Hi @rpitingolo. Thanks for raising this. It was really most valuable for smaller geographies, so I would probably remove it from all the summary files going forward. I'm not sure if those variables were ever used elsewhere. Can you do a quick scan to see if they appear in other code? @lhendey @ahariharan7

**Comment by rpitingolo** [comment]
@ptatian Sure. I did a scan on Friday and as far as I can tell those variables were not used as denominators or anywhere else in variable construction. I think they were included on the summary file more as a FYI. We will proceed with not including them on 2020 and newer updates. 

@ahariharan7 @lhendey

**Comment by rpitingolo** [comment]
@ahariharan7 I updated the macros to account for the change in unweighted counts. Can you please make sure the header is updated in all 4 programs and then re-run and double check the logs, please? Thanks!

**Comment by rpitingolo** [comment]
@ahariharan7 all looks good. Please go ahead and merge/sync/batch submit final programs on SAS1. Thanks!

**Pull request merged**
