### PR TITLE
Creating geo summary file updates for WV, MD, and VA

### PR DESCRIPTION
**Pull request by ahariharan7**

### CODE REVIEW

**Comment by ahariharan7** [comment]
@rpitingolo ready for your review!

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I'll review.

**Comment by ahariharan7** [comment]
@rpitingolo just went through!

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I'll review again now.

**Review by rpitingolo — APPROVED** [review]

**Comment by rpitingolo** [comment]
@ahariharan7 nice job and thanks for editing the bug in the macro. Please go ahead and merge, sync and final batch submit this one. Thanks!

**Pull request merged**
