### PR TITLE
Added tables to acs_sf file

### PR DESCRIPTION
**Pull request by sdiby**
Tables include B25072, B25074, B25093, B25095, B08007, and B08012.

B25095 is not available at the blockgroup level.

### CODE REVIEW

**Comment by sdiby** [comment]
@ptatian this is ready for your review.

**Comment by ptatian** [comment]
@sdiby Thanks, Somala. I will review.

**Comment by ptatian** [comment]
@sdiby Are you planning to run this update for the 2011-15 ACS data only (Acs_sf_2011_15_dc.sas)? Or do we need it for any earlier years? (I'm assuming we do not, but wanted to make sure.)

**Comment by sdiby** [comment]
@ptatian I don't recall the BP team requesting data for earlier years, so I've been planning to run this only for the 2011-15 ACS data

**Comment by sdiby** [comment]
@ptatian I batch submitted for DC and errors came up: it looks like the file path to the raw data has changed, and lives in two new folders "DistrictofColumbia_All_Geographies_Not_Tracts_Block_Groups" and "DistrictOfColumbia_Tracts_Block_Groups_Only". Since the data lives in two folders with different geographies, how would you advise referencing it in the code?

**Comment by ptatian** [comment]
@sdiby Hmm...yes. That's not actually the problem. The problem was in the metadata system. Looks like the file now has too many variables! When trying to register the metadata an error was generated, and that caused SAS to go into debug mode so it didn't process anything after that. 

```
ERROR: The length of the value of the macro variable NUM_VARS (65540) exceeds the maximum length (65534). The value has 
       been truncated to 65534 characters.
NOTE: The SAS System stopped processing this step because of errors.
```

I've pushed a temporary fix to to the **Acs_sf_2011_15_dc.sas, Acs_sf_2011_15_md.sas, Acs_sf_2011_15_va.sas,** and **Acs_sf_2011_15_wv.sas** programs. You should sync and copy the new programs to L: and submit. You'll be able to create the data sets that you need but they won't get updated in the metadata. We'll have to figure out a better solution later. 

@rpitingolo, CC'ing you so that you are aware of this problem.

**Pull request merged**
