### PR TITLE
Bugfix #103

### PR DESCRIPTION
**Pull request by lhendey**

### CODE REVIEW

**Comment by lhendey** [comment]
@ptatian - i changed the subsetting. Also I don't think there are any uninitialized vars re: #74

**Comment by ptatian** [comment]
Thanks, @lhendey. I will review.

**Comment by ptatian** [comment]
@lhendey This still doesn't seem right. Shouldn't all three summary files for MD, VA, WV include the same counties?

**Comment by lhendey** [comment]
@ptatian - i don't necessarily think so. I'm okay if the tract and county files include the whole states (feels like there could be a reason we'd want to do all of maryland - or look at nearby jurisdictions?)

**Comment by ptatian** [comment]
@lhendey For example, **ACS_2012_16_WV_sum_tr_tr10** and **ACS_2012_16_WV_sum_regcnt_regcnt** include all WV counties, but **ACS_2012_16_WV_sum_tr_regcd** has only Jefferson Co.  cc: @rpitingolo

**Comment by lhendey** [comment]
@ptatian - yes, i understand. I would prefer to have all counties and tracts in the state but don't see the purpose of having all counties in the council district file since we'd just be adding them as whole counties rather than figuring out whether they have districts or not. cc @rpitingolo

**Comment by lhendey** [comment]
@rpitingolo - could you address @ptatian  comment, I haven't worked much with the formats

"Code looks fine but I recommend changing the labeling of the county data sets and adding a format to the County variable to make clear that those files include all counties. "

**Comment by rpitingolo** [comment]
@lhendey OK, so this is a change that needs to happen in the General library, right? Not on this issue? @ptatian

**Comment by rpitingolo** [comment]
@ptatian OK. I'm not going to work on this today. I am plugging away at the vital stats stuff and I know you and Yipeng will need that soon.

**Comment by ptatian** [comment]
@rpitingolo Understood. @lhendey If you want to go ahead and finish this up, that's fine. We can create a new issue for the labeling/format change since that is not critical.

**Comment by lhendey** [comment]
@ptatian yes, thanks will do. cc @rpitingolo

**Pull request merged**
