### PR TITLE
Develop #42

### PR DESCRIPTION
**Pull request by Liposey**

### CODE REVIEW

**Comment by Liposey** [comment]
In ACS_summary_geo_source, it had created separate variables for tract and block group. I switched the language from creating variables specific to tract geography to make it create variables for whenever it wasn't a block group so that the county would be included.

**Comment by rpitingolo** [comment]
@Liposey thanks. I"ll review.

**Comment by rpitingolo** [comment]
@Liposey please merge this pull request and then copy and run the following to L:
In the macros folder: ACS_summary_all.sas, ACS_summary_geo.sas, ACS_summary_geo_source.sas
In the prog folder: ACS_2011_15_dc_sum_all.sas, ACS_2011_15_md_sum_all.sas, ACS_2011_15_va_sum_all.sas

@ptatian it took quite a few edits to the above ACS macros to get these to run properly for the VA and MD files and with the new county geography. Hopefully my edits are straightforward, let me know if you have any questions.

**Comment by ptatian** [comment]
Thanks, Rob. Not a serious problem, but the %File_info is redundant when using %Finalize_data_set. %Finalize_data_set automatically runs a %File_info.

**Comment by rpitingolo** [comment]
@ptatian thanks, I didn't know that. I'll check for that in the future.

**Pull request merged**
