### PR TITLE
Update #141 add median hh income to summary table

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo Hi Rob I get an error when I ran the dc_sum_all program, so basically it couldn't find the new variables I added for 2017. These variables are new and shouldn't be existing in the 12-16 file. I somewhat know how to fix this in the ACS_summary_geo program but not exactly sure, could you take a look? @lhendey

**Comment by maggiesu0725** [comment]
@rpitingolo nevermind I think I know how to fix it. Thanks!

**Comment by maggiesu0725** [comment]
@rpitingolo ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 the programs run, but there are some duplicate variables in the %let moeallyears= statement that's producing warnings in the log. We should get that cleaned up, but I know this is on a tight timeline.
@lhendey OK to do the cleanup now or do you want Yipeng to finalize and move to the next task?

**Comment by lhendey** [comment]
@maggiesu0725 it sounds like fixing the dup vars wouldn't take very long so pleas do it now. @rpitingolo

**Comment by maggiesu0725** [comment]
@rpitingolo I couldn't find where the duplicate variable MedHHIncm_ was introduced, this is the last one.

**Comment by maggiesu0725** [comment]
resolved, ready for review. @rpitingolo  In case you can have a quick review today so I could proceed. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 go ahead and merge. please batch submit on L.  cc @rpitingolo

**Pull request merged**
