### PR TITLE
Racial equity sf 2010 14

### PR DESCRIPTION
**Pull request by sdiby**
New ACS 2010-2014 tables have been added to existing lists (table_list
and drop_bg_list), including new variables and race breakouts of
existing variables. Certain tables have been deleted from drop_list to
accommodate newly pulled tables.

One warning appears in the log for B23002. Estimates in this table are
used to calculate the employed population aged 25-64. As far as I know,
this is the only table we can use to ascertain this variable. It's not
in NIDC and appears to be suppressed by the Census.

Early on, we thought errors in the acs_sf_2010_14_dc program were caused
by the length of the tables lists. The text file is a back-up of a
program Leah wrote to solve the errors (we didn't end up using it).

### CODE REVIEW

**Comment by lhendey** [comment]
Somala - please remove table B23002 (doesn't exist in the 5 year data). Add a line in the program header under the description that says
Modifications:  SD  080116  Added tables needed for Racial Equity Profile.

**Comment by lhendey** [comment]
@ptatian Peter - @sdiby is going to make a few small changes as I noted in the comment above, then it would be ready to be merged. However the branch has conflicts - how do we resolve those?

**Comment by ptatian** [comment]
@lhendey @sdiby OK, I will take a look.

**Comment by sdiby** [comment]
@lhendey @ptatian This is just an FYI that I've removed B23002 and made the modification note, so the program is ready to be merged.

**Pull request closed without merging**
