### PR TITLE
Update ACS_summary_geo_source_tr_vars.sas 

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo  I'm not sure why there's a conflict in ACS_summary_geo.sas, all three macros are updated to include additional variables for Stac tables

**Comment by rpitingolo** [comment]
@maggiesu0725 can you please test using D:\DCData\Libraries\ACS\Prog\SF_2012_16\ACS_2012_16_dc_sum_all.sas ? I will look at the conflict and see what the issue is.

**Comment by rpitingolo** [comment]
@ptatian Hi Peter. What's the best way to resolve the branch conflicts in a situation like this? I'm a little weary to use the web editor and potentially mess something up. Thanks. @maggiesu0725

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 I think the best way probably is to use the [web editor](https://github.com/NeighborhoodInfoDC/ACS/pull/108/conflicts). It looks to me like you want to keep the code that between the `<<<<<<< develop-#107` and `=======` markers. Just delete those markers and everything between `=======`  and `>>>>>>> master`. I would then test the edited code before merging. The changes will be another commit so you can always undo it, if needed.

**Comment by rpitingolo** [comment]
@ptatian thanks. So when you use the web editor to make a change, then sync the branch the program on D will reflect the changes on the web? Seems simple enough. Thanks. @maggiesu0725

**Comment by ptatian** [comment]
@rpitingolo Yes, that should be the way it works. The commit to resolve the conflicts will be on the remote (origin) and you'll need to pull it into your local branch.

**Comment by rpitingolo** [comment]
@ptatian thanks. I think I got it resolved.
@maggiesu0725 can you please pull fetch origin and then re-test. thanks!

**Comment by rpitingolo** [comment]
@maggiesu0725 I made two commits. The errors were happening because in a few places you forgot to add the semicolon (;) to the end of the line of code. In one case there was an extra comma. Can you please check that nothing was supposed to go after that comma? You can see the line in my commits. Thanks!

**Comment by rpitingolo** [comment]
@maggiesu0725 Go ahead and merge, sync and close this issue. Make sure to batch submit the Acs_sf_2012_16_dc Acs_sf_2012_16_md Acs_sf_2012_16_va Acs_sf_2012_16_wv programs first.

**Pull request merged**
