### PR TITLE
Create all ACS summary data sets for 2014-18

### PR DESCRIPTION
**Pull request by rpitingolo**
@NeighborhoodInfoDC/review ready for review.

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo what about planning areas?

**Comment by rpitingolo** [comment]
@lhendey we are finishing the last step now. So if you're OK waiting to finalize this issue until tomorrow then it can be included.

**Comment by lhendey** [comment]
@rpitingolo would prefer inclusion if we are that close. will review the rest of it.

**Comment by rpitingolo** [comment]
@lhendey OK sure, you can at least review the MD, VA and WV as they don't use that code.

**Comment by lhendey** [comment]
@rpitingolo  is it weird that there are different N's for this variable? (cltr00) 
MedRent5plusbd_2014_18              13        32191.00         2476.23         2396.05               0         6965.00
MedRent4bd_2014_18                  25       118373.00         4734.92         5007.44               0        18679.00
MedRent3bd_2014_18                  39       239653.00         6144.95         5823.31               0        27762.00
MedRent2bd_2014_18                  39       296119.00         7592.79         5330.54     721.0000000        24842.00
MedRent1bd_2014_18                  40       228225.00         5705.63         3875.75     878.0000000        17007.00
MedRent0bd_2014_18                  34       132991.00         3911.50         2957.97               0        10231.00

**Comment by lhendey** [comment]
@rpitingolo i guess some geographies have missing vs. zeros?

**Comment by rpitingolo** [comment]
@lhendey the cluster geos are a little quirky. I'll take a look.

**Comment by lhendey** [comment]
@rpitingolo not just on clusters - typically on median income or median rent or aggregate income.

**Comment by lhendey** [comment]
@rpitingolo if you can confirm that variation in counts is just a feature and not a bug (also on other states) the rest looks good to go.

**Comment by rpitingolo** [comment]
@lhendey I checked on this and confirmed that some cells are read in as missing on the SF files. If you look up the median rent by bedroom (B25031e7) on data.census.gov the cells are missing for both the estimate and moe whereas when you lookup bedrooms by tenure (B25042) it shows 0 counts with an moe for the corresponding cells. So that would explain the inconsistency. 

I added  the NPA and am going to merge and finalize this now.

**Pull request merged**
