### PR TITLE
Update #173

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo I don't need to explicitly define which variables I want to include in the pull if I define the tables I want, right? Just define the vars I don't want to include?

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 I think that's right. Going to take a look.

**Comment by rpitingolo** [comment]
@ahariharan7 please make sure to pull changes first as I reversed one of your previous commits. Since you added the new tables to the macro you don't need to include them in each individual state program. I edited the DC program, so take a look at how that looks and then you can edit the other states to look the same. Re-run each of them and then I'll do a final review.

Don't worry about the summary programs for now. We will do those in a second issue.

**Comment by ahariharan7** [comment]
@rpitingolo ready for your review!

**Comment by rpitingolo** [comment]
@ahariharan7 thanks I will take a look.

**Comment by rpitingolo** [comment]
@ahariharan7 Good to go. Please go ahead and merge this branch, sync and batch submit the four _sf programs. We'll tackle the summary programs in the next issue.

**Pull request merged**
