### PR TITLE
add table B11004 to ACS varlist

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo ready for review

**Comment by lhendey** [comment]
@maggiesu0725 - let me know if you've gotten this working and need a review. You'd need to update the MD, VA and WV programs as well as DC.

**Comment by maggiesu0725** [comment]
@lhendey thanks, I think I've updated these three programs/macros: ACS_sumamry_geo; ACS_2012_16_dc_sum_all; and summary_geo_source_tr_vars but the summary program is not running properly, it will say a lot of variables are missing which I don't know is due to which program not functioning. It would  be great if you could take a look at it, if not I will try to investigate a bit more. I'll update the program for MD, VA and WV once this is working.

**Comment by maggiesu0725** [comment]
Variable names are fixed and the program runs correctly. I've updated the ACS summary program for MD VA and WV as well. Ready for review @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 code looks good - but could you change the naming convention slightly for the male and female-headed vars?

It would make more sense to have   NumFam**MHR**KidsU6_&_years. than NumFamRKidsU6_**mh**_&_years.

**Comment by lhendey** [comment]
@maggiesu0725 thanks, okay to merge.

**Pull request merged**
