### PR TITLE
trying to fix uninitialized var issue, but after adding tables to acs_sf, the vars are still popping up as uninitialized

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo can you please review when you have a second?

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 thanks. I will review.

**Comment by ahariharan7** [comment]
@rpitingolo changes reverted, then added in again - ready for your review!

**Comment by ahariharan7** [comment]
@rpitingolo

**Comment by rpitingolo** [comment]
@ahariharan7 can you confirm that this is the full list of variables that shows as uninitialized in the other program? `B18107 B18101H B18101B B18101D B18101E B18101I B18101C C25074 C25095`

C25074 and C25095 do not appear available on the 2015-19 5-year data. They are one-year estimates and in some older 5-year estimates. So you will have to find an alternative (in  the B tables preferably) or not include these in the summary indicators.

**Comment by ahariharan7** [comment]
@rpitingolo found the 5 year equivalents! ready for your review

**Comment by rpitingolo** [comment]
@ahariharan7 Great. Will check it now.

**Comment by rpitingolo** [comment]
@ahariharan7 looks good now. Let's go ahead and finalize this one so you can turn back to the summary indicators.

**Pull request merged**
