### PR TITLE
shortening var names in ACS_summary_geo

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo shortening var names, but not sure how to address the error on invalid value for keep option?

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 sounds like that second error isn't actually an error? I'll take a look at the code with the shortened var names. Thanks!

**Comment by rpitingolo** [comment]
@ahariharan7 I am still getting variable exceeds 32 character errors when I run any of the state summary programs. Can you please do a control-F for "32 characters" in the log to make sure we catch all of them? There are other errors in the log but those might stem from the 32 character errors, so let's get rid of those first and if it still doesn't run clean we can investigate the other errors.

**Comment by ahariharan7** [comment]
@rpitingolo Thanks! Caught an errant variable when running MD. I think we are ok now (cross your fingers).

**Comment by rpitingolo** [comment]
@ahariharan7 I am still getting errors when running the summary programs. I will try to take a closer look and see what is causing them.

**Comment by rpitingolo** [comment]
@ahariharan7 In the log I see these errors. I believe this is the result of your fixing the variables that exceeded 32 characters. The variables in the ACS_summary_geo macro should match your new names exactly. Once they do then these errors will go away and the program should run clean. 

```
ERROR: The variable NumSingFam: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable MedGRentPercInc_: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable HIncInt: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable RentBurden: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable NRentBurden: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable MedOwnerCosts: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable CostBurden: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable NCostBurden: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable OwnerOcc: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable RenterOcc: in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumSingFamUnits_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumSingFamRentalUnits_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumSingFamOwnerOccUnits_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mMedGRentPercInc_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mAvgHHSizeRenterOcc_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mAvgHHSizeOwnerOcc_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccessL10KwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccessL10KwoInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess1019KwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess1019KwoInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess2034KwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess2034KwoInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess3549KwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess3549KwoInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess5074KwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess5074KwoInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess75MwInt_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mHIncIntAccess75Mw0Int_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwAmbulatoryDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwoAmbulatoryDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwCognitiveDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwoCognitiveDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwVisionDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwoVisionDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwHearingDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNumwoHearingDiff_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurdenUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurdenUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurden10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurden10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurden20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurden20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurden35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurden35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurden50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurden50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBurden75KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurden75KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mMedOwnerCostsPctHHInc_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurdenUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurdenUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden75999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden75999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurden100KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBurden100KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHIncL5K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc5999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc101499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc151999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc202499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc253499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc354999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc507499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc759999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc10014999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccHHInc150M_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHIncL5K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc5999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc101499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc151999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc202499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc253499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc354999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc507499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc759999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc10014999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccHHInc150M_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccMovedIn201516_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccMovedIn201014_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccMovedIn200009_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOccMovedIn199099_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccMovedIn201516_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccMovedIn201014_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccMovedIn200009_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOccMovedIn199099_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOcc1SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOcc2SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOcc3SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOcc4SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mOwnerOcc0SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOcc1SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOcc2SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOcc3SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOcc4SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRenterOcc0SubstCond_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
```

**Comment by ahariharan7** [comment]
@rpitingolo ready for your review!

**Comment by ahariharan7** [comment]
@rpitingolo updated variables in git! ready for your review.

**Comment by rpitingolo** [comment]
@ahariharan7. Thanks. I'll give it a look.

**Comment by rpitingolo** [comment]
@ahariharan7 there is a small bug in the sf macro where B18101E is in both the keep and the drop list. I'm going to fix that on the other branch and then re-test this code.

**Comment by rpitingolo** [comment]
@ahariharan7 OK there are still a few problems that need to be fixed. I am getting uninitialized variable warnings for these: `B18107e29 B18107e32 B18107e30 B18107e33 B18107m29 B18107m32 B18107m30 B18107m33 B1810421 B181032m11 B2507010`

The B18107 table only goes up to cell 27, so please check and adjust your variables in %ACS_summary_geo_source_tr_vars so they calculate correctly. 

B1810421 appears to be a typo and should be B18104m-something.

B181032m11 appears to be a typo and should be B18102m11

B2507010 appears to be a typo and should be B25070m10

In the next data step I am getting these errors which are preventing the datastep from running:

ERROR: The variable mRentBurUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBurUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBur10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBur10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBur20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBur20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBur35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBur35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBur50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBur50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mRentBur75KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNRentBur75KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBurUnder10K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur10199K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur20349K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur35499K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur50749K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur75999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur75999K_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mCostBur100KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.
ERROR: The variable mNCostBur100KMore_2015_19 in the DROP, KEEP, or RENAME list has never been referenced.

It looks like your commit from yesterday renamed some variables, and now the variables in %ACS_geo_source keep statement are out of sync again. Once you correct them the program should run through.

**Comment by ahariharan7** [comment]
@rpitingolo for your review!

**Comment by rpitingolo** [comment]
@ahariharan7 it appears you are creating a variable called NumwoCognitiveDiff_&_years. but then trying to label a variable called NumwoCogDiff_&_years. which is causing an uninitialized warning.

**Comment by ahariharan7** [comment]
@rpitingolo If the notes aren't an issue then here's the code for your review.

**Comment by rpitingolo** [comment]
@ahariharan7 almost there. I think the only thing left is to update the `revisions = %str` message in the four summary programs

**Comment by ahariharan7** [comment]
@rpitingolo Updated revisions note!

**Comment by rpitingolo** [comment]
@ahariharan7 great! Let's go ahead and merge and finalize this one.

**Comment by ptatian** [comment]
Thank you, @ahariharan7 and @rpitingolo for getting this across the finish line!

**Pull request merged**
