### PR TITLE
update acs summary files

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo updating the sum_all programs for all 4 states. i think there are geography issues with these programs as well. i looked into the acs_summary_all macro (whcih the sum_all programs call) and it calls:  %ACS_summary_geo_source( bg10 ) **** Create summary files from census tract source ****; %ACS_summary_geo_source( tr10 ) and then when i go into that macro that has a lot of 2020 geographies missing... are you able to update these macros? cc @lhendey

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eburton9 I'll take a look at the macros. It sounds like we need to make some updates for 2020 geos.

**Comment by rpitingolo** [comment]
@eburton9 I updated the macros. You need to add ` census_geo_year = 2020` parameter to the main program for each state. Give it a try and we'll go from there.

**Comment by eburton9** [comment]
@rpitingolo thank you! i added that to all four programs. bad news is my laptop is still having sas/vpn issues.. is there anyway you could run one or two and lmk if it works?

**Comment by eburton9** [comment]
@rpitingolo okay it finished after 30 minutes but there are lots and lots of "ERROR: The variable mNumRentCstBurden_15_24_2016_20 in the DROP, KEEP, or RENAME list has never been referenced."

**Comment by lhendey** [comment]
@eburton9 @rpitingolo had to make a couple tweaks to the geo_source macro. wv runs now but DC doesn't. here's the log if one of you has time to look at it. 
[ACS_2016_20_dc_sum_all.log](https://github.com/NeighborhoodInfoDC/ACS/files/10519497/ACS_2016_20_dc_sum_all.log)

**Comment by lhendey** [comment]
@rpitingolo i think it's more missing crosswalks to 2020 geos.

**Comment by rpitingolo** [comment]
@lhendey is the issue that we are trying to re-summarize the data in 2000 and 2010 tracts? Do we need the data at those geographies?

**Comment by lhendey** [comment]
@rpitingolo i think it's trying to create geographies like bridge park when we haven't set up cross-walks for 2020 for them? (have we?)  I commented out the councildist on the regional side because those cross walks definitely don't exist (and there would be new council boundaries that we don't have).

**Comment by rpitingolo** [comment]
@lhendey we should have crosswalks to all previously existing standard geographies (so geo2020 to bridgepark should work). If it's not then something else is going wrong. We don't have crosswalks to things like geo2020 to ANC2022 yet.

**Comment by lhendey** [comment]
@rpitingolo - okay - i edited code so EOR, Geo2000 and Geo2010 are only called for pre2020 geos. But we don't have a wt file for 2020 bg to 2020 tr which we need? (still getting error on DC) - missing wt file.

**Comment by rpitingolo** [comment]
@lhendey OK I'll look into the missing weight. Not sure why it would be missing.

**Comment by lhendey** [comment]
@rpitingolo i got no errors on logs now that we have that weight file. okay to merge?

**Comment by rpitingolo** [comment]
@lhendey yes OK to merge.

**Pull request merged**
