### PR TITLE
Add special value recodes and close #214

### LINKED ISSUE #214: Replace MOEs with -555555555 as 0
https://www.census.gov/data/developers/data-sets/acs-1year/data-notes.html 

Possible values
-555555555

-555555555.0

-555555555.00

Edit compile_acs_new.sas macro in the section:
 ** Recode margin of error = -1 to .N (not available) **;
    **** CENSUS HAS NEW CODES FOR MOE VALUES ;
    **** CURRENTLY THOSE CODES ARE LEFT AS IS AND NOT RECODED TO SAS MISSING VALUES ;
    
    array moe{*} &table_m_list;
    
    do i = 1 to dim( moe );
    
      if moe{i} = -1 then moe{i} = .n;
      
    end;

### PR DESCRIPTION
**Pull request by ptatian**

### CODE REVIEW

**Comment by ptatian** [comment]
@lhendey I think I have a fix for the ACS special code issue (#214). Would you please review and let me know if this works for what you need? 

You will notice that some variables will end up with missing values or MOEs for certain observations.

**Review by lhendey — APPROVED** [review]
@ptatian looks like it should work. do you want to edit the revision statement on the sum programs too? (Or i can do that and finalize).

**Comment by ptatian** [comment]
@lhendey Ah, yes. Good idea! Thanks for thinking of the revisions statement. Happy to pass things over to you to wrap up.

**Comment by ptatian** [comment]
Sorry for this causing problems earlier.

**Comment by lhendey** [comment]
@ptatian no worries, weird that we weren't picking up all of these before.

**Pull request merged**
