### PR TITLE
2012_16 ACS DC update

### PR DESCRIPTION
**Pull request by chedman**

### CODE REVIEW

**Comment by rpitingolo** [comment]
@chedman this looks good. Please merge, batch submit on L, and then move on to the next issue.

**Comment by chedman** [comment]
@rpitingolo Ok great. In the new github desktop, should I select "merge into current branch"?

**Comment by rpitingolo** [comment]
@chedman I'm actually not sure what that does (yet). For now just use "merge pull request" on the web.

**Comment by chedman** [comment]
@rpitingolo great, just merged

**Pull request merged**
