### PR TITLE
Created vars for cost burden by age, income; employment commute

### PR DESCRIPTION
**Pull request by sdiby**
Created vars for renter and homeowner cost-burdened households by age of household and income level of householder.

Also created vars for workers 16 and over; whether or not they work in or outside of their state of residence.

And vars for workers 16 and over who don't work at home, by commute time.

### CODE REVIEW

**Comment by sdiby** [comment]
@ptatian ready for your review

**Comment by ptatian** [comment]
@sdiby Please let me know when you've batch submitted Acs_sf_2011_15_dc.sas. I can't properly review these changes until the new tables have been added to the data.

**Comment by ptatian** [comment]
@sdiby I think things might have gotten a little confused because we are working on two branches. Changes in one branch won't appear in the other branch unless they are merged. For instance, I see that the Acs_sf.sas macro code on L: does not have the updates from the data-#69 branch. If you copied the version of the program from the data-#70 branch, that would explain it. 

So, let's proceed as follows: 

1. Merge [pull request #71](https://github.com/NeighborhoodInfoDC/ACS/pull/71) 
2. Go to the GitHub app and switch to the Master branch
3. Update your local repo Master by syncing
4. Copy the updated programs and macros to L: 
5. Batch submit the programs Acs_sf_2011_15_dc.sas, Acs_sf_2011_15_md.sas, Acs_sf_2011_15_va.sas, Acs_sf_2011_15_wv.sas, 
6. Check that they run OK

Tell me when that's done, so I can verify as well, and then we can move on to the next step.

**Comment by ptatian** [comment]
@sdiby I noticed the uninitialized median family income vars, too. I didn't want to take time fixing them right now since we were pressed. We can create a new issue to fix that later.

**Comment by sdiby** [comment]
@ptatian I've proceeded as you've outlined--logs are ready on the L: for you to verify.

**Comment by ptatian** [comment]
Thanks, @sdiby. I've closed issue #69. We can now finish up this issue. Please:

1. Merge this pull request
2. Go to the GitHub app and switch to the Master branch
3. Update your local repo Master by syncing
4. Copy the updated programs and macros to L:
5. Batch submit the programs Acs_2011_15_dc_sum_all.sas, Acs_2011_15_md_sum_all.sas, Acs_2011_15_va_sum_all.sas, Acs_2011_15_wv_sum_all.sas.
6. Check that they run OK

I can double-check once you've finished.

**Comment by sdiby** [comment]
Hi @ptatian I'm still encountering the same variable initialization issue, even with the updated programs. All acs_sf and sum_all progs for DC, MD, VA, and WV are updated and batch submitted on the L: for your review.

**Comment by ptatian** [comment]
Thank you, @sdiby. These look fine, and I'm closing out issue #70. I made new issue #74 to address the uninitialized variable problems.

**Pull request merged**
