### PR TITLE
Update ACS_summary_geo_source_tr_vars.sas

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo Can you please check to make sure I added the variables correctly when you have a second? I added MedGrossRent and DisabilityStatusY (and their corresponding MOEs). Once I get your okay I'll add in the rest of the variables I need.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 I'll take a look at these.

**Comment by rpitingolo** [comment]
@ahariharan7 On the right track. Please double check the B181013 variables as it looks like you have a typo and it should be B18101. For the MOE you should use the `%moe_sum(var=)` syntax rather than the simple `sum()` syntax that you use for the estimate. Labels look good.

**Comment by ahariharan7** [comment]
@rpitingolo Updated and ready for your check!

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I will give it a look.

**Comment by rpitingolo** [comment]
@ahariharan7 This is kind of annoying the but the syntax for the MOE is different than the estimate. For the MOE you need to use the var= inside the the parenthesis and no commas. So for your variable it should be:

`%moe_sum(var= B18101m4 B18101m7 B18101m10 B18101m13 B18101m16 B18101m19 B18101m23 B18101m26 B18101m29, B18101m32 B18101m35 B18101m38);`

Rather than

`%moe_sum(B18101m4, B18101m7, B18101m10, B18101m13, B18101m16, B18101m19, B18101m23, B18101m26, B18101m29, B18101m32, B18101m35, B18101m38);`

**Comment by ahariharan7** [comment]
@rpitingolo feeling good about this one! ready for your review

**Comment by rpitingolo** [comment]
Looks like you got it! Please go ahead with creating your other variables. Don't forget you also need to add your new indicators to the  Acs_summary_geo.sas macro.

**Comment by ahariharan7** [comment]
@rpitingolo new code here ready for your review!

**Comment by rpitingolo** [comment]
@ahariharan7 it looks like we have a branch conflict. This might be related to the git push issue you had? I can take a look to see what's up.

**Comment by rpitingolo** [comment]
@ahariharan7 a few updates.

1. I fixed your branch conflict.
2. One of the variables that used %moesum() was missing the closing parentheses which was causing some errors. Looks like it was just one instance so I just fixed it.
3. Some of your variable names are too long. Annoyingly, in SAS, your variables are limited to 32 characters. This includes 8 characters needed for the suffix _2015_19. I recommend running ACS_2015_19_md_sum_all. There will be errors in the log but you will be able to identify all of the variables with names that needed shortened.

**Comment by ahariharan7** [comment]
@rpitingolo Okay! Shortened the offending var names and ready for your review.

**Comment by rpitingolo** [comment]
@ahariharan7 great! I will give it a look.

**Comment by rpitingolo** [comment]
@ahariharan7 I am still getting some 32 character errors. Try running ACS_2015_19_md_sum_all.sas and you should see them all in the log.

**Comment by ahariharan7** [comment]
@rpitingolo another try!

**Comment by rpitingolo** [comment]
@ahariharan7 thanks, I'll give it a look!

**Pull request merged**
