### PR TITLE
add new tables to ACS_sf

### PR DESCRIPTION
**Pull request by maggiesu0725**
add new tables. Please review. @lhendey

### CODE REVIEW

**Comment by lhendey** [comment]
@maggiesu0725 missing a step. see step c at the end of this box note.

**Comment by ptatian** [comment]
@maggiesu0725 @lhendey Conflict in this merge relates to changes that I just made to the ACS programs on master (see issue #152). You should resolve by keeping both sets of changes.

**Comment by lhendey** [comment]
@maggiesu0725 - i don't see the commits on the revisions. also please see peter's comment.

**Comment by maggiesu0725** [comment]
committed the change to a wrong branch, sorry about that. Conflict should be resolved. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 okay to merge. charge 100001-0001-010-00003-Improvements on Greaterdc.urban.org for time on this request

**Pull request merged**
