### PR TITLE
Add indicators for digital access to 2013-17 summary files

### PR DESCRIPTION
**Pull request by maggiesu0725**
update ACS_summary_geo_source_tr_vars & Acs_summary_geo

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@lhendey @rpitingolo ready for review

**Comment by lhendey** [comment]
@maggiesu0725 need to update the revisions statements in all the ...ss_sum_all.sas files.

**Comment by lhendey** [comment]
@maggiesu0725 = there are a number of errors in the log to resolve first-  you should get a clean run before requesting review.  you also need to your the %moe_sum macro for the MOEs.  which is %moe_sum(var=...)

**Comment by maggiesu0725** [comment]
so when I ran the ACS_2013_17_dc_sum_all new variables are not showing up because they are uninitialized. acs_sf macro has been updated to include the tables these variables are from. I don't know whereelse I should check for the uninitialized error? thanks!! @rpitingolo @lhendey

**Comment by maggiesu0725** [comment]
Thank you so much for the help! I think these programs are ready for review again. ACS_2013_17_dc_sum_all ACS_2013_17_md_sum_all ACS_2013_17_va_sum_all ACS_2013_17_wv_sum_all 
@rpitingolo

**Comment by rpitingolo** [comment]
@maggiesu0725 Please correct this the in the macro which is causing an uninitialized variable. `NumnocomputerA_&_years.= sum(B28009De63, B28009Ee6);`

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. You can go ahead and merge, sync and batch submit these programs.

**Pull request merged**
