### PR TITLE
Update #168

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo ready for your review!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I will review.

**Comment by rpitingolo** [comment]
@ahariharan7 I made a few updates to the MD program. Can you copy those over to the others and re-run / re-test to make sure it all works? Then tag me for another review.

B00001 and B00002 are no longer included in this ACS update. I added B98001, B98002, and B98003 as recommended alternatives. 

Thanks!

**Comment by ahariharan7** [comment]
@rpitingolo all yours!

**Comment by rpitingolo** [comment]
@ahariharan7 going to look at it now.

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! Let's go ahead and merge the pull request, sync on \\sas1\ and batch submit the 4 programs.

**Pull request merged**
