### PR TITLE
Update ACS Sum files

### PR DESCRIPTION
**Pull request by eburton9**
@lhendey I'm having an error with the file not reading the macro file I edited in my local drive.. it looks like it may be an issue with the higher up macro used.. I don't know if that even makes sense but I didn't see anywhere in either SummaryFile_All_Macro or Acs_sd_2016_20_DC for a file path to my local drive. Please let me know if you have follow ups or if I should redirect this question t to Rob or someone else. Thanks!

### CODE REVIEW

**Comment by eburton9** [comment]
@rpitingolo I'm having an error with my local drive and don't see the file path in either program I was editing. Could you look into this? Thanks!

**Comment by rpitingolo** [comment]
@eburton9 can you past the error message that you are getting? I am able to run the program but getting some invalid geography errors that we will need to address.

**Comment by rpitingolo** [comment]
I am getting these warnings as well.

```
WARNING: The variable B00001e: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable B00002e: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable C25074e: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable C25095e: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable B00001m: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable B00002m: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable C25074m: in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable C25095m: in the DROP, KEEP, or RENAME list has never been referenced.
```

Doe we know if these variables don't exist any more on the 2016-20 data?

**Comment by eburton9** [comment]
I'm getting `ERROR: Cannot open %INCLUDE file D:\DCData\Libraries\ACS\Prog\SF_2016_20\SummaryFile_All_Macro.sas.` first, then `ERROR: Cannot open %INCLUDE file D:\DCData\Libraries\ACS\Raw\SF_2016_20\Code\edc_0001.sas.` followed by 0002 through 0143. Later I get `ERROR: File WORK.G20205DC.DATA does not exist.` as many times as the previous errors (same issue i'm guessing).

**Comment by eburton9** [comment]
@rpitingolo I don't see any reference to changes to those variables on this [web page for modified/new tables](https://www.census.gov/programs-surveys/acs/technical-documentation/table-and-geography-changes/2020/5-year.html#modified-tables). Also based on the [2020 ACS 5-year Detailed Table Shells](https://www2.census.gov/programs-surveys/acs/summary_file/2020/documentation/user_tools/ACS2020_Table_Shells.xlsx) I don't see any B00001 or B00002 variable and for C25074 and C25095 there is nothing with an M or E on the end, just additional numbers for different incomes.

**Comment by eburton9** [comment]
@rpitingolo after changing my local drive and re running (tried twice), i get the strange window log full error and have to close the window, so not able to see the errors in the log and it doesn't give me an output.

**Comment by rpitingolo** [comment]
@eburton9 batch submit the program and then you can see the full log in the .log file.

**Comment by eburton9** [comment]
@rpitingolo okay I'm getting a lot of ERROR: [Compile_ACS] Invalid geography value: _N_=207 GEOID=15000US110010001011 GeoBg2010=110010001011 in two different places

**Comment by rpitingolo** [comment]
@eburton9 I am guessing that is because this ACS data uses the 2020 definitions and not 2010?

**Comment by eburton9** [comment]
@rpitingolo Yeah that's what I was thinking. Would geo changes and variable changes be made in: D:\DCData\Libraries\ACS\Macros\Acs_sf.sas ? I'm looking at these instructions [https://urbanorg.box.com/s/qejvsul03ecv4u8xny3xftjtdot0xeo3] at the bottom.

**Comment by rpitingolo** [comment]
@eburton9 seems like there are a few things going on. I think you still have a problem with your environment. I'm not able to replicate the %include errors or t he physical file does not exist warning. Is the repo cloned on your D drive? This is probably something weird happening with Windows. You might try to restart your computer and make sure the D drive is working correctly.

I am getting some invalid geography errors on the compile_acs macro so we will have to open that up to see what's going on. This is independent of the environment issues though.

**Comment by eburton9** [comment]
@rpitingolo erg i checked and it's cloned on my D drive. Also restarted my computer and same errors. How do I make sure my D drive is working correctly?

**Comment by lhendey** [comment]
@rpitingolo this ran fine for me on my desktop - okay to merge? i didn't see any errors in log and skimmed output cc @eburton9

**Comment by rpitingolo** [comment]
@lhendey Did all 4 programs run? I was only checking DC but that was OK if you were able to run without errors.

**Comment by lhendey** [comment]
@rpitingolo i checked DC & WV.

**Comment by lhendey** [comment]
@rpitingolo okay - i ran VA fine (remotely logged into my desktop) but errors on MD. 
[Acs_sf_2016_20_VA.log](https://github.com/NeighborhoodInfoDC/ACS/files/10490790/Acs_sf_2016_20_VA.log)
[Acs_sf_2016_20_MD.log](https://github.com/NeighborhoodInfoDC/ACS/files/10490791/Acs_sf_2016_20_MD.log)

**Comment by eburton9** [comment]
@lhendey @rpitingolo flagging that the errors in the MD log "cannot open %INCLUDE file" are the ones that I've been dealing with

**Comment by lhendey** [comment]
@rpitingolo thanks! md runs clean for me now. I'm going to merge. cc @eburton9

**Comment by eburton9** [comment]
@lhendey @rpitingolo neither of you were receiving errors that their were variables that didn't exist? I remember that being an issue too.

**Comment by rpitingolo** [comment]
@eburton9 was it an error or warning? I see uninitialized warnings about those variables that I posted up in the previous comment.

**Comment by eburton9** [comment]
@rpitingolo you're right, the same warnings you have. did someone batch submit this onto sas1? thinking testing the program on that would be helpful for the errors i keep having..

**Comment by lhendey** [comment]
@eburton9 @rpitingolo ran all 4 states successfully, i wasn't seeing "uninitialized" in the log at all.

**Pull request merged**
